package ru.ritual.app.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.dp

private sealed interface MarkdownBlock {
    data class Paragraph(val text: String) : MarkdownBlock
    data class Heading(val level: Int, val text: String) : MarkdownBlock
    data class ListItem(val marker: String, val text: String, val checked: Boolean? = null) : MarkdownBlock
    data class Quote(val text: String) : MarkdownBlock
    data class Code(val text: String) : MarkdownBlock
    data class Table(val rows: List<String>) : MarkdownBlock
    data object Divider : MarkdownBlock
}

/** Compact renderer for the Markdown generated by YandexGPT and entered in step notes. */
@Composable
fun MarkdownText(
    markdown: String,
    modifier: Modifier = Modifier,
    style: TextStyle = MaterialTheme.typography.bodyLarge,
    color: Color = MaterialTheme.colorScheme.onSurface,
) {
    if (markdown.isBlank()) return
    val blocks = remember(markdown) { parseMarkdown(markdown) }
    Column(modifier = modifier, verticalArrangement = Arrangement.spacedBy(5.dp)) {
        blocks.forEach { block ->
            when (block) {
                is MarkdownBlock.Heading -> Text(
                    inlineMarkdown(block.text, color),
                    style = when (block.level) {
                        1 -> MaterialTheme.typography.headlineMedium
                        2 -> MaterialTheme.typography.titleLarge
                        else -> MaterialTheme.typography.titleMedium
                    },
                    color = color,
                )
                is MarkdownBlock.Paragraph -> Text(inlineMarkdown(block.text, color), style = style, color = color)
                is MarkdownBlock.ListItem -> Row(verticalAlignment = Alignment.Top) {
                    Text(
                        when (block.checked) {
                            true -> "☑"
                            false -> "☐"
                            null -> block.marker
                        },
                        style = style,
                        color = color,
                    )
                    Spacer(Modifier.size(8.dp))
                    Text(inlineMarkdown(block.text, color), style = style, color = color, modifier = Modifier.weight(1f))
                }
                is MarkdownBlock.Quote -> Row(
                    Modifier.fillMaxWidth().background(Color.White.copy(alpha = .38f), RoundedCornerShape(7.dp)),
                ) {
                    Box(Modifier.size(width = 3.dp, height = 38.dp).background(color.copy(alpha = .42f)))
                    Text(
                        inlineMarkdown(block.text, color),
                        style = style.copy(fontStyle = FontStyle.Italic),
                        color = color.copy(alpha = .82f),
                        modifier = Modifier.padding(horizontal = 10.dp, vertical = 8.dp),
                    )
                }
                is MarkdownBlock.Code -> Text(
                    block.text,
                    style = MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace),
                    color = color,
                    modifier = Modifier.fillMaxWidth().horizontalScroll(rememberScrollState())
                        .background(Color.Black.copy(alpha = .07f), RoundedCornerShape(7.dp)).padding(10.dp),
                )
                is MarkdownBlock.Table -> Text(
                    block.rows.joinToString("\n") { it.trim().trim('|').split('|').joinToString("  │  ") { cell -> cell.trim() } },
                    style = MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace),
                    color = color,
                    modifier = Modifier.fillMaxWidth().horizontalScroll(rememberScrollState())
                        .background(Color.White.copy(alpha = .35f), RoundedCornerShape(7.dp)).padding(9.dp),
                )
                MarkdownBlock.Divider -> HorizontalDivider(color = color.copy(alpha = .18f))
            }
        }
    }
}

private fun parseMarkdown(markdown: String): List<MarkdownBlock> {
    val lines = markdown.replace("\r\n", "\n").lines()
    val result = mutableListOf<MarkdownBlock>()
    var index = 0
    while (index < lines.size) {
        val raw = lines[index]
        val line = raw.trim()
        when {
            line.isBlank() -> index++
            line.startsWith("```") -> {
                val code = mutableListOf<String>()
                index++
                while (index < lines.size && !lines[index].trim().startsWith("```")) code += lines[index++]
                if (index < lines.size) index++
                result += MarkdownBlock.Code(code.joinToString("\n"))
            }
            line.startsWith("|") && line.endsWith("|") -> {
                val rows = mutableListOf<String>()
                while (index < lines.size && lines[index].trim().let { it.startsWith("|") && it.endsWith("|") }) {
                    val row = lines[index++].trim()
                    if (!row.replace("|", "").replace("-", "").replace(":", "").isBlank()) rows += row
                }
                if (rows.isNotEmpty()) result += MarkdownBlock.Table(rows)
            }
            line.matches(Regex("^#{1,3}\\s+.*")) -> {
                val level = line.takeWhile { it == '#' }.length
                result += MarkdownBlock.Heading(level, line.drop(level).trim())
                index++
            }
            line == "---" || line == "***" || line == "___" -> {
                result += MarkdownBlock.Divider
                index++
            }
            line.startsWith(">") -> {
                result += MarkdownBlock.Quote(line.removePrefix(">").trim())
                index++
            }
            line.matches(Regex("^[-*+]\\s+\\[[ xX]]\\s+.*")) -> {
                val checked = line.substringAfter('[').firstOrNull()?.lowercaseChar() == 'x'
                result += MarkdownBlock.ListItem("•", line.substringAfter(']').trim(), checked)
                index++
            }
            line.matches(Regex("^[-*+]\\s+.*")) -> {
                result += MarkdownBlock.ListItem("•", line.drop(2).trim())
                index++
            }
            line.matches(Regex("^\\d+[.)]\\s+.*")) -> {
                val marker = line.substringBefore(' ').trimEnd('.', ')') + "."
                result += MarkdownBlock.ListItem(marker, line.substringAfter(' ').trim())
                index++
            }
            else -> {
                result += MarkdownBlock.Paragraph(line)
                index++
            }
        }
    }
    return result
}

private fun inlineMarkdown(source: String, color: Color): AnnotatedString = buildAnnotatedString {
    var index = 0
    fun appendStyled(open: String, close: String, style: SpanStyle): Boolean {
        if (!source.startsWith(open, index)) return false
        val end = source.indexOf(close, index + open.length)
        if (end < 0) return false
        pushStyle(style)
        append(source.substring(index + open.length, end))
        pop()
        index = end + close.length
        return true
    }
    while (index < source.length) {
        when {
            appendStyled("**", "**", SpanStyle(fontWeight = FontWeight.Bold)) -> Unit
            appendStyled("__", "__", SpanStyle(fontWeight = FontWeight.Bold)) -> Unit
            appendStyled("~~", "~~", SpanStyle(textDecoration = TextDecoration.LineThrough)) -> Unit
            appendStyled("`", "`", SpanStyle(fontFamily = FontFamily.Monospace, background = color.copy(alpha = .1f))) -> Unit
            source[index] == '*' && appendStyled("*", "*", SpanStyle(fontStyle = FontStyle.Italic)) -> Unit
            source[index] == '_' && appendStyled("_", "_", SpanStyle(fontStyle = FontStyle.Italic)) -> Unit
            source[index] == '[' -> {
                val labelEnd = source.indexOf("](", index)
                val urlEnd = if (labelEnd >= 0) source.indexOf(')', labelEnd + 2) else -1
                if (labelEnd > index && urlEnd > labelEnd) {
                    pushStyle(SpanStyle(color = Color(0xFF245D91), textDecoration = TextDecoration.Underline))
                    append(source.substring(index + 1, labelEnd))
                    pop()
                    index = urlEnd + 1
                } else {
                    append(source[index++])
                }
            }
            source[index] == '\\' && index + 1 < source.length -> {
                index++
                append(source[index])
                index++
            }
            else -> append(source[index++])
        }
    }
}
